const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('#main-nav');
toggle?.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Close navigation':'Open navigation');nav.classList.toggle('open',open)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Open navigation');toggle.focus()}});
const form=document.querySelector('#enquiry-form');
if(form){
 const fields=document.querySelector('#conditional-fields');
 const text=(label,name,required=false)=>`<label>${label}<input name="${name}" ${required?'required':''}></label>`;
 const select=(label,name,options)=>`<label>${label}<select name="${name}"><option value="">Please select</option>${options.map(x=>`<option>${x}</option>`).join('')}</select></label>`;
 function render(){const type=form.elements.type.value;fields.innerHTML=type==='school'?'<div class="field-grid">'+text('Role','role')+text('School','school',true)+'</div><div class="field-grid">'+select('Type of support','support',['Curriculum & Assessment Review','Teaching & Learning','Department Development','Professional Development','Not sure yet'])+text('Preferred timeframe','timeframe')+'</div>':type==='tuition'?'<div class="field-grid">'+select('Student year group','year',['Year 7','Year 8','Year 9','Year 10','Year 11','Year 12','Year 13','Other'])+select('Subject','subject',['A Level Physics','GCSE Physics','GCSE Chemistry','GCSE Combined Science','KS3 Science','KS3 Maths','Other'])+'</div><div class="field-grid">'+text('Examination board, if known','board')+text('Preferred availability','availability')+'</div>'+text('Current situation / support required','situation'):'';document.querySelector('#email-confirmation').hidden=true;}
 const params=new URLSearchParams(location.search),type=params.get('type');if(['school','tuition','other'].includes(type))form.elements.type.value=type;render();if(params.get('support')==='review'&&form.elements.support)form.elements.support.value='Curriculum & Assessment Review';form.querySelectorAll('[name=type]').forEach(el=>el.addEventListener('change',render));
 form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const data=new FormData(form);const labels={type:'Enquiry type',name:'Name',email:'Email',role:'Role',school:'School',support:'Support',timeframe:'Timeframe',year:'Year group',subject:'Subject',board:'Examination board',availability:'Availability',situation:'Current situation',message:'Message'};const body=Array.from(data).filter(([k,v])=>v).map(([k,v])=>`${labels[k]||k}: ${v}`).join('\n\n');document.querySelector('#email-copy').value=body;document.querySelector('#email-confirmation').hidden=false;window.location.href='mailto:hello@stemcoach.uk?subject='+encodeURIComponent('The STEM Coach — '+({school:'School consultancy',tuition:'Private tuition',other:'General enquiry'}[data.get('type')]))+'&body='+encodeURIComponent(body);});
 document.querySelector('#copy-email').addEventListener('click',async()=>{const box=document.querySelector('#email-copy');try{await navigator.clipboard.writeText(box.value);document.querySelector('#copy-status').textContent='Enquiry copied.'}catch{box.focus();box.select();document.querySelector('#copy-status').textContent='Select and copy the enquiry text.'}});
}
